### ISSUE TITLE
Де використовується цей метод?

### ISSUE THREAD

**Issue by ivan-yermolenko** [RikiBob/donate-backend#2]
https://github.com/RikiBob/donate-backend/blob/228c289746ae676f5efb6d83c8899bbed3f0bb37/src/modules/auth/auth.service.ts#L116

**Comment by RikiBob** [comment]
Не використовується. Планував дещо, а потім забув видалити Sent from my iPhoneOn 23 Sep 2024, at 23:17, SinfulServant ***@***.***> wrote:﻿
https://github.com/RikiBob/donate-backend/blob/228c289746ae676f5efb6d83c8899bbed3f0bb37/src/modules/auth/auth.service.ts#L116

**Comment by RikiBob** [comment]
Вибач, я тебе обманув, він використовується в validate jwt.strategy Sent from my iPhoneOn 23 Sep 2024, at 23:17, SinfulServant ***@***.***> wrote:﻿
https://github.com/RikiBob/donate-backend/blob/228c289746ae676f5efb6d83c8899bbed3f0bb37/src/modules/auth/auth.service.ts#L116
